simplesocial/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
# So 'views.py' does not get mixed up with the line above, we give it an alias with "import as"

from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name="accounts/logout.html"), name="logout"),
    path("signup/", views.SignUp.as_view(), name='signup'),
]

simplesocial/posts/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path('', views.PostList.as_view(), name="all"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path("accounts/", include('accounts.urls', namespace='accounts')),
    path("groups/", include('groups.urls', namespace='groups')),
    path("posts/", include('posts.urls', namespace='posts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", views.HomePage.as_view(), name='home'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug/', include(debug_toolbar.urls))
    ] + urlpatterns

simplesocial/templates/base.html
<!doctype html>
{% load static %}
<html lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>UAH Pikes</title>
        <!--<meta name="description" content="">-->
        <!--<meta name="viewport" content="width=device-width, initial-scale=1">-->

        <!--<link rel="manifest" href="site.webmanifest">-->
        <!--<link rel="apple-touch-icon" href="icon.png">-->
        <!-- Place favicon.ico in the root directory -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

        <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}"/>

        <!--<link rel="stylesheet" href="css/main.css">-->
    </head>

    <body>
        <nav class="navbar navbar-inverse" role="navigation" id="navbar">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand mynav" href="{% url 'home' %}">Rocket City Pikes</a>
                </div>
                <div class="nav justify-content-end">
                  {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'posts:all' %}" >Pike Feed</a>
                    <a class="nav-item nav-link" href="{% url 'posts:create' %}" >Create Post</a>
                    <a class="nav-item nav-link" href="{% url 'groups:all' %}">Community</a>
                    <a class="nav-item nav-link" href="{% url 'groups:create' %}" >Create Community</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                  {% else %}
                    <a class="nav-item nav-link" href="{% url 'groups:all' %}">Groups</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:login' %}">Log in</a>
                    <a class="nav-item nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
                  {% endif %}
                </div>
            </div>
        </nav>
        <!--[if lte IE 9]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
        [endif]-->

        <!-- Add your site or application content here -->
    <div class="container mycontent">
    {% block body_block %}





    {% endblock %}
    </div>

<canvas id="canvas"></canvas>

        <!--<script src="js/vendor/modernizr-3.5.0.min.js"></script>-->
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script type="text/javascript" src="{% static 'simplesocial/js/master.js' %}"></script>
        <!--<script>window.jQuery || document.write('<script src="js/vendor/jquery-3.2.1.min.js"><\/script>')</script>-->
        <!--<script src="js/plugins.js"></script>-->
        <!--<script src="js/main.js"></script>-->

        <!--&lt;!&ndash; Google Analytics: change UA-XXXXX-Y to be your site's ID. &ndash;&gt;-->
        <!--<script>-->
            <!--window.ga=function(){ga.q.push(arguments)};ga.q=[];ga.l=+new Date;-->
            <!--ga('create','UA-XXXXX-Y','auto');ga('send','pageview')-->
        <!--</script>-->
        <!--<script src="https://www.google-analytics.com/analytics.js" async defer></script>-->
    </body>
</html>

simplesocial/templates/index.html
{% extends 'base.html'%}
{% load staticfiles %}
{% block body_block %}
<h1>Home Page Text</h1>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

{% endblock %}

simplesocial/templates/test.html
{% extends 'base.html'%}

{% block body_block %}
    {% block content%}
        <h1>You are now logged in.</h1>
    {% endblock %}
{% endblock %}

simplesocial/templates/thanks.html
{% extends 'base.html'%}

{% block body_block %}
    {% block content%}
        <h1>You are now logged out.</h1>
    {% endblock %}
{% endblock %}