simplesocial/posts/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path("by/<username>/",views.UserPosts.as_view(),name="for_user"),
    path("by/<username>/<int:pk>/",views.PostDetail.as_view(),name="single"),
    path("delete/<int:pk>/",views.DeletePost.as_view(),name="delete"),
    path("new/", views.CreatePost.as_view(), name="create"),
    path('', views.PostList.as_view(), name="all"),
]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path("accounts/", include('accounts.urls', namespace='accounts')),
    path("groups/", include('groups.urls', namespace='groups')),
    path("posts/", include('posts.urls', namespace='posts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("", views.HomePage.as_view(), name='home'),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug/', include(debug_toolbar.urls))
    ] + urlpatterns

simplesocial/posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from groups.models import Group
from django.utils.text import slugify

import misaka

# Create your models here.

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    title = models.CharField(max_length=255)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.title_html = misaka.html(self.title)
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', kwargs={'username': self.user.username,
                                               'pk': self.pk})
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

simplesocial/posts/views.py
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (LoginRequiredMixin, PermissionRequiredMixin)
from django.urls import reverse_lazy
from django.http import Http404
from django.views.generic import (TemplateView, ListView,
                                  DetailView, CreateView,
                                  UpdateView, DeleteView)
from braces.views import SelectRelatedMixin

from . import models

from django.contrib.auth import get_user_model
User = get_user_model()

class PostList(SelectRelatedMixin, ListView):

    model = models.Post
    select_related = ('user', 'group')

class UserPosts(ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related("posts").get(
                username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin, DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, CreateView):

    fields = ('title', 'message', 'group')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, DeleteView):

    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id = self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

simplesocial/posts/templates/posts/_post.html
<div class="post media">
    <div class="media-body">
        <h1 class='media-heading'>
            <h2><strong>{{ post.title }}</strong></h2>
            <p>Submitted by
                <a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a>
                on <time class="time">{{ post.created_at }}</time>
            </p>
            <h4>{{ post.message_html|safe }}</h4>
        </h1>
    </div>
</div>

<div class="media-footer">
    {% if user.is_authenticated and post.user == user and not hide_delete %}
    <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-simple">
        <span class="glyphicon glyphicon-remove text-danger icon-label" aria-hidden="true">Delete This Post</span>
    </a>
    {% endif %}
</div>

simplesocial/posts/templates/posts/post_base.html
{% extends 'base.html' %}

{% block body_block %}
    <div class="posts-page">
        <div class="posts-page">
            <div class="posts-page">
                {% block prepost %}{% endblock %}
                {% block post_content %}{% endblock %}
                {% block post_post %}{% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

simplesocial/posts/templates/posts/post_confirm_delete.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<h3>Are you sure you want to delete this post?</h3>

<div class="posts">
	{% include "posts/_post.html" with post=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-default btn-large">Cancel</a>
</form>

{% endblock %}

simplesocial/posts/templates/posts/post_detail.html
{% extends "posts/post_base.html" %}

{% block post_content %}
<!-- <div class="col-md-8"> -->
    {% include "posts/_post.html" %}
<!-- </div> -->
{% endblock %}

simplesocial/posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap4 %}

{% block post_content %}
    <h4>Create a new post here!</h4>
    <form method="POST" action="{% url 'posts:create' %}" id="postForm">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary btn-large" value="Post">
    </form>
{% endblock %}

simplesocial/posts/templates/posts/post_list.html
{% extends "posts/post_base.html" %}

{% block pre_post_content %}
    <div class="col-md-4">
        <div class="col-md-4">
            {% if request.user.is_authenticated %}
            <div class="card card-with-shadow">
                <div class="content">
                    <h5 class="title">Your Groups</h5>
                    <ul class="list-unstyled">
                        <!-- we add 'get_' to user groups (defined in models.py) to get members of user groups -->
                        {% for member in get_user_groups %}
                            <li class="group li-with-bullet"><a href="{% url 'groups:single' slug=member_group.group.slug %}"></a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            {% endif %}

            <div class="card card-with-shadow">
                <div class="content">
                    <h5 class="title">All Groups</h5>
                    <ul class="list-unstyled">
                        {% for other_group in get_other_groups %}
                            <li class="group li-with-bullet"><a href="{% url 'groups:single' slug=other_group.slug %}">{{ other_group.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block post_content %}
    <div class="col-md-8">
        {% for post in post_list %}
            {% include "posts/_post.html" %}
        {% endfor %}
    </div>
{% endblock %}

simplesocial/posts/templates/posts/user_post_list.html
{% extends "posts/post_base.html" %}

{% block prepost %}
    <div class="col-md-4">
        <h2>All Posts by @{{post_user.username}}</h2>
    </div>
{% endblock %}

{% block post_content %}
    <div class="col-md-8">
        <hr>
        {% for post in post_list %}
            {% include 'posts/_post.html' %}
        {% endfor %}

    </div>
{% endblock %}